In [3]:
import numpy as np

A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

#行列の積を計算
gyouretu = np.dot(A, B)
#行列の積を表示
print(gyouretu)
#行列の最大値を表示
gyouretu.max()

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


47